import formlogo from "../public/application.png"

export const json = {
  title: "Patient Registration Form",
  description:
    "Your privacy is important to us. All information received through our forms and other communications is subject to our Patient Privacy Policy.",
  logo: formlogo,
  logoWidth: "auto",
  logoHeight: "50",
  completedHtml:
    '<div style="max-width:540px;text-align:left;margin:0px auto 16px auto;border: 1px solid rgba(0,0,0,0.25);padding:40px 48px 48px 48px;background-color:#fff;">\n\n<h4>Thank you for completing your patient registration form.</h4>\n<br>\n<p>Dear {firstname-for-complete-page},\n<br>\nYour information has been successfully received, and we look forward to providing you with the highest level of care. \n<br><br>\nIf you have any questions , please don\'t hesitate to reach out to the hospital . Our doctors and staff are there to assist you every step of the way.\n',
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "panel",
          name: "personal-information",
          elements: [
            {
              type: "text",
              name: "first-name",
              width: "50%",
              minWidth: "256px",
              title: "First Name",
            },
            {
              type: "text",
              name: "last-name",
              width: "50%",
              minWidth: "256px",
              startWithNewLine: false,
              title: "Last Name",
            },
            {
              type: "text",
              name: "birthdate",
              width: "50%",
              minWidth: "256px",
              startWithNewLine: false,
              title: "Date of Birth",
              inputType: "date",
            },
            {
              type: "dropdown",
              name: "gender",
              width: "50%",
              minWidth: "256px",
              startWithNewLine: false,
              title: "Gender",
              choices: ["Male", "Female"],
              choicesOrder: "random",
              placeholder: "",
              allowClear: false,
            },
          ],
          width: "69%",
          minWidth: "256px",
        },
        {
          type: "file",
          name: "photo",
          width: "31%",
          imageWidth: "532",
          imageHeight: "576",
          minWidth: "256px",
          startWithNewLine: false,
          titleLocation: "hidden",
          sourceType: "Local files",
          photoPlaceholder: " ",
        },
        {
          type: "panel",
          name: "contact-information",
          elements: [
            {
              type: "text",
              name: "address",
              width: "66%",
              minWidth: "256px",
              title: "Address",
            },
            {
              type: "text",
              name: "city",
              width: "34%",
              minWidth: "128px",
              title: "City",
            },
            {
              type: "text",
              name: "state",
              width: "32%",
              minWidth: "128px",
              startWithNewLine: false,
              title: "State",
            },
            {
              type: "text",
              name: "pin",
              width: "34%",
              minWidth: "128px",
              startWithNewLine: false,
              title: "Pin Code",
            },
            {
              type: "text",
              name: "phone",
              width: "34%",
              minWidth: "128px",
              title: "Phone #",
            },
            {
              type: "text",
              name: "email",
              width: "66%",
              minWidth: "256px",
              startWithNewLine: false,
              title: "Email Address",
            },
          ],
          title: "Contact Information",
          width: "100%",
          minWidth: "256px",
        },
        {
          type: "panel",
          name: "organ-donation",
          elements: [
            {
              type: "dropdown",
              name: "Blood-group",
              width: "30%",
              minWidth: "50px",
              title: "Blood-Group",
              choices: ["A+","A-","AB+","AB-","B+","B-","O","O+"],
              allowClear: false,
            },
            
            {
              type: "text",
              name: "Age",
              inputType: "number",
              min: 0,
              max: 120,
              width: "30%",
              startWithNewLine: false,
              minWidth: "50px",
              title: "Age",
            },
            {
              type: "text",
              name: "bmi",
              inputType: "number",
              min: 0,
              max: 50,
              width: "30%",
              minWidth: "50px",
              startWithNewLine: false,
              title: "BMI(Body Mass Index)",
            },
            {
              type: "text",
              name: "organ-type",
              minWidth: "50px",
              maxWidth: "40%",
              title: "Organ-type",
            },
            {
              type: "dropdown",
              name: "patient-type",
              minWidth: "50px",
              maxWidth: "40%",
              startWithNewLine: false,
              choices: ["Donor","Recipient"],
              allowClear: false,
              title: "Patient-type",
            },
          ],
          title: "Organ-Donation Details",
          width: "100%",
          minWidth: "256px",
        },
        
      ],
    },
  ],
  calculatedValues: [
    {
      name: "firstname-for-complete-page",
      expression: "iif({first-name} notempty, {first-name}, patient)",
    },
  ],
  showQuestionNumbers: "off",
  questionErrorLocation: "bottom",
  completeText: "Register",
  questionsOnPageMode: "singlePage",
  widthMode: "static",
  width: "1024",
  fitToContainer: true,
};
